---
title: "ProyectoTD2026"
author: "GrupoH"
date: "`r Sys.Date()`"
output: html_document
---

**Simple Summary:** En este proyecto, analizaremos un conjunto de datos real el cual corresponde a los registros de actividad de la asignatura "Tratamiento de Datos" del curso 2024-2025. El trabajo se centra en transformar los datos brutos en información útil, para poder ver como interactúan los estudiantes con los materiales del curso.

**Abstract:** Este trabajo aborda la Fase1 del análisis de los registros de Moodle de la asignatura "Tratamiento de Datos". Nuestro objetivo principal ha sido el procesamiento del dataset proporcionado mediante R, en donde nos hemos centrado en su limpieza de los registros y la estructura de las variables. A parte, con los graficos podemos ver los primeros patrones en el comportamiento de los alumnos.


**Palabras clave:** Análisis, Moodle, R, limpieza de datos, Tratamiento de Datos.

#1.Introduccion

#2.Importación y limpieza de datos.
-En esta parte se realiza la carga del conjunto de datos original y se aplican las transformaciones necesarias para su posterior análisis. Esto implica la conversión de los tipos de datos y la eliminación de aquellos registros que no nos resulten relevantes.

```{r}
library(tidyverse)

logs <- read_csv("logs_moodle_anon.csv.zip", col_types = cols(Hora = col_datetime(format = "%d/%m/%y, %H:%M:%S")))

view(logs)

```


#3.Análisis y visualización de datos.

#4.Preguntas.

- ¿ En qué días de la semana hay más picos de actividad?

- ¿Cuáles son las horas a las que prefieren estudiar los alumnos de "Tratamiento de datos"?







